(defun bisiesto ()
  (princ "Por favor, ingresa un año: ")
  (setq anio (read))
  (if (and (zerop (mod anio 4))
           (or (not (zerop (mod anio 100)))
               (zerop (mod anio 400))))
      (format t "El año ~A es bisiesto.~%" anio)
      (format t "El año ~A no es bisiesto.~%" anio)))
(bisiesto)